#!/bin/bash
# Generated by Copilot
# Test script for ForgeHeadless HTTP API

# Start the server in the background
./forge-headless > server.log 2>&1 &
SERVER_PID=$!

echo "Server started with PID $SERVER_PID. Waiting for initialization..."
sleep 15

# Check if server is still running
if ! ps -p $SERVER_PID > /dev/null; then
    echo "Server failed to start. Check server.log:"
    cat server.log
    exit 1
fi

echo "Server log tail:"
tail -n 10 server.log

echo ""
echo "=== Testing GET /state ==="
curl -s http://localhost:8081/state | head -20
echo ""

echo ""
echo "=== Testing GET /input ==="
INPUT_JSON=$(curl -s http://localhost:8081/input)
echo "$INPUT_JSON" | head -20
echo ""

# Extract the action count
COUNT=$(echo "$INPUT_JSON" | grep -o '"count":[0-9]*' | cut -d: -f2)
PASS_INDEX=$((COUNT - 1))

echo ""
echo "=== Testing POST /action (pass priority, index=$PASS_INDEX) ==="
curl -s -X POST -H "Content-Type: application/json" -d "{\"index\": $PASS_INDEX}" http://localhost:8081/action
echo ""

echo "Waiting for game to process..."
sleep 3

echo ""
echo "=== GET /state after passing priority ==="
curl -s http://localhost:8081/state | head -10
echo ""

echo ""
echo "=== Testing POST /control (concede) ==="
curl -s -X POST -H "Content-Type: application/json" -d '{"command": "concede"}' http://localhost:8081/control
echo ""

# Kill the server
kill $SERVER_PID 2>/dev/null
echo ""
echo "=== Test Complete ==="
