const { test, expect } = require('@playwright/test');
const { launchDesktop } = require('./support/desktop.cjs');
const path = require('node:path');
const fs = require('node:fs');
test('desktop beta supports a complete deck-building workflow', async () => {
  const { application, appPath, dataPath, executable } = await launchDesktop('desktop');
  const errors = [];
  try {
    const page = await application.firstWindow();
    page.on('pageerror', error => errors.push(error.message));
    await expect(page.locator('#loading')).toBeHidden({ timeout: 60000 });
    await expect(page.locator('#deck-name')).toHaveValue('First spark');
    await expect(page.locator('#main-count')).toHaveText('60');
    await expect(page.locator('#validation')).toContainText('Deck structure looks good');
    await expect(page.locator('#search')).toHaveValue('');
    await expect(page.locator('#catalog-scope')).toContainText('Full library');
    const total = await page.locator('#result-count').innerText();
    expect(Number(total.replace(/\D/g, ''))).toBeGreaterThan(33000);
    await expect(page.locator('#catalog .catalog-card')).toHaveCount(24);
    await page.locator('#next').click();
    await expect(page.locator('#page-label')).toHaveText(/^25–48 of /);
    await page.locator('#search').fill('Lightning');
    await expect(page.locator('#result-count')).toHaveText(/\d+ of [\d,]+ cards/);
    await page.locator('#type-filter').selectOption('Instant');
    await page.locator('#mana-filter').selectOption('1');
    await page.locator('[data-color="8"]').click();
    await page.locator('#clear-filters').click();
    await expect(page.locator('#search')).toHaveValue('');
    await expect(page.locator('#type-filter')).toHaveValue('');
    await expect(page.locator('#mana-filter')).toHaveValue('');
    await expect(page.locator('[data-color].active')).toHaveCount(0);
    await expect(page.locator('#result-count')).toHaveText(total);
    await expect(page.locator('#page-label')).toHaveText(/^1–24 of /);
    await page.locator('#search').fill('Insectile Aberration');
    await expect(page.locator('#catalog .catalog-card').first()).toContainText('Delver of Secrets');
    await page.locator('#search').fill('The Eon Fog');
    await expect(page.locator('#catalog .catalog-card').first()).toContainText('The Eon Fog');
    await page.locator('#catalog button[data-add]').first().click();
    await expect(page.locator('#supplemental-section')).toHaveValue('Planes');
    await expect(page.locator('#deck-list')).toContainText('The Eon Fog');
    await expect(page.locator('#main-count')).toHaveText('60');
    await page.locator('[data-section=Main]').click();
    await page.locator('#supplemental-section').selectOption('Planes');
    await expect(page.locator('#deck-list')).toContainText('The Eon Fog');
    await page.locator('#undo').click();
    await page.locator('[data-section=Main]').click();
    await expect(page.locator('#supplemental-toolbar')).toBeHidden();
    await page.locator('#clear-filters').click();
    // Invisible packaged windows can stall Chromium's screenshot compositor.
    // Capture in source runs; keep every interaction assertion in both modes.
    if (!executable) await page.screenshot({ path: path.join(appPath, 'test-results/workshop.png') });
    await page.locator('#search').fill('Llanowar Elves');
    await expect(page.locator('#catalog .catalog-card').first()).toContainText('Llanowar Elves');
    await page.locator('#catalog button[data-add]').first().click();
    await expect(page.locator('#main-count')).toHaveText('61');
    await page.locator('#undo').click();
    await expect(page.locator('#main-count')).toHaveText('60');
    await page.locator('#redo').click();
    await expect(page.locator('#main-count')).toHaveText('61');
    await page.locator('#deck-name').fill('Beta test deck');
    await page.locator('#deck-name').press('Enter');
    await expect(page.locator('.library-deck.active')).toContainText('Beta test deck');
    await page.locator('[data-section=Sideboard]').click();
    await page.locator('#catalog button[data-add]').first().click();
    await expect(page.locator('#side-count')).toHaveText('1');
    await page.locator('#import-button').click();
    await page.locator('#import-text').fill('4 Definitely Not A Real Card XYZ');
    await page.locator('#preview-import').click();
    await expect(page.locator('#import-preview')).toContainText('Resolve these lines');
    await expect(page.locator('#confirm-import')).toBeDisabled();
    await page.locator('#import-text').fill('Deck\n4 Lightning Bolt\n56 Mountain\nSideboard\n2 Shock');
    await page.locator('#import-name').fill('Imported beta');
    await page.locator('#preview-import').click();
    await expect(page.locator('#confirm-import')).toBeEnabled();
    await page.locator('#confirm-import').click();
    await expect(page.locator('#import-dialog')).not.toBeVisible();
    await expect(page.locator('#deck-name')).toHaveValue('Imported beta');
    await expect(page.locator('#main-count')).toHaveText('60');
    await page.locator('#practice-button').click();
    await expect(page.locator('.hand-card')).toHaveCount(7);
    await page.locator('#draw-card').click();
    await expect(page.locator('.hand-card')).toHaveCount(8);
    await page.locator('[data-bottom]').first().click();
    await expect(page.locator('.hand-card')).toHaveCount(7);
    if (!executable) await page.screenshot({ path: path.join(appPath, 'test-results/practice.png') });
    await page.locator('#back-workshop').click();
    await page.locator('#export-button').click();
    await expect(page.locator('#export-text')).toHaveValue(/56 Mountain/);
    await page.locator('#copy-export').click();
    expect(await application.evaluate(({ clipboard }) => clipboard.readText())).toContain('56 Mountain');
    const exportedFile = path.join(dataPath, 'exported.dck');
    await application.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, exportedFile);
    await page.locator('#save-forge').click();
    await expect(page.locator('#toast')).toContainText('Forge deck exported');
    expect(fs.readFileSync(exportedFile, 'utf8')).toContain('[Main]');
    await page.locator('#export-dialog .icon-button').click();
    await page.reload();
    await expect(page.locator('#loading')).toBeHidden();
    await expect(page.locator('#deck-name')).toHaveValue('Imported beta');
    await expect(page.locator('#side-count')).toHaveText('2');
    await page.locator('#import-button').click();
    await application.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, exportedFile);
    await page.locator('#import-file').click();
    await expect(page.locator('#confirm-import')).toBeEnabled();
    await page.locator('#import-dialog .icon-button').click();
    await page.locator('#new-sidebar').click();
    await page.locator('#new-name').fill('Commander project');
    await page.locator('#new-format').selectOption('Commander');
    await page.locator('#new-form button[type=submit]').click();
    await expect(page.locator('#commander-section')).toBeVisible();
    await expect(page.locator('#practice-button')).toBeDisabled();
    expect(errors).toEqual([]);
    expect(fs.readdirSync(path.join(dataPath, 'decks')).filter(file => file.endsWith('.json'))).toHaveLength(3);
  } finally { await application.close(); }
});
