const { test, expect, _electron: electron } = require('@playwright/test');
const path = require('node:path');
const fs = require('node:fs');
test('desktop beta supports a complete deck-building workflow', async () => {
  const appPath = path.resolve(__dirname, '..');
  const dataPath = path.join(appPath, 'test-results', `desktop-${Date.now()}`);
  const errors = [];
  const environment = { ...process.env, FORGE_TEST: '1', FORGE_USER_DATA: dataPath, FORGE_OFFLINE: '1' };
  delete environment.ELECTRON_RUN_AS_NODE;
  const application = await electron.launch({ args: [appPath], env: environment });
  try {
    const page = await application.firstWindow();
    page.on('pageerror', error => errors.push(error.message));
    await expect(page.locator('#loading')).toBeHidden({ timeout: 60000 });
    await expect(page.locator('#deck-name')).toHaveValue('First spark');
    await expect(page.locator('#main-count')).toHaveText('60');
    await expect(page.locator('#validation')).toContainText('Deck structure looks good');
    await page.screenshot({ path: path.join(appPath, 'test-results/workshop.png') });
    await page.locator('#search').fill('Llanowar Elves');
    await expect(page.locator('#catalog .catalog-card').first()).toContainText('Llanowar Elves');
    await page.locator('#catalog button[data-add]').first().click();
    await expect(page.locator('#main-count')).toHaveText('61');
    await page.locator('#undo').click();
    await expect(page.locator('#main-count')).toHaveText('60');
    await page.locator('#redo').click();
    await expect(page.locator('#main-count')).toHaveText('61');
    await page.locator('#deck-name').fill('Beta test deck');
    await page.locator('#deck-name').press('Enter');
    await expect(page.locator('.library-deck.active')).toContainText('Beta test deck');
    await page.locator('[data-section=Sideboard]').click();
    await page.locator('#catalog button[data-add]').first().click();
    await expect(page.locator('#side-count')).toHaveText('1');
    await page.locator('#import-button').click();
    await page.locator('#import-text').fill('4 Definitely Not A Real Card XYZ');
    await page.locator('#preview-import').click();
    await expect(page.locator('#import-preview')).toContainText('Resolve these lines');
    await expect(page.locator('#confirm-import')).toBeDisabled();
    await page.locator('#import-text').fill('Deck\n4 Lightning Bolt\n56 Mountain\nSideboard\n2 Shock');
    await page.locator('#import-name').fill('Imported beta');
    await page.locator('#preview-import').click();
    await expect(page.locator('#confirm-import')).toBeEnabled();
    await page.locator('#confirm-import').click();
    await expect(page.locator('#import-dialog')).not.toBeVisible();
    await expect(page.locator('#deck-name')).toHaveValue('Imported beta');
    await expect(page.locator('#main-count')).toHaveText('60');
    await page.locator('#practice-button').click();
    await expect(page.locator('.hand-card')).toHaveCount(7);
    await page.locator('#draw-card').click();
    await expect(page.locator('.hand-card')).toHaveCount(8);
    await page.locator('[data-bottom]').first().click();
    await expect(page.locator('.hand-card')).toHaveCount(7);
    await page.screenshot({ path: path.join(appPath, 'test-results/practice.png') });
    await page.locator('#back-workshop').click();
    await page.locator('#export-button').click();
    await expect(page.locator('#export-text')).toHaveValue(/56 Mountain/);
    await page.locator('#copy-export').click();
    expect(await application.evaluate(({ clipboard }) => clipboard.readText())).toContain('56 Mountain');
    const exportedFile = path.join(dataPath, 'exported.dck');
    await application.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, exportedFile);
    await page.locator('#save-forge').click();
    await expect(page.locator('#toast')).toContainText('Forge deck exported');
    expect(fs.readFileSync(exportedFile, 'utf8')).toContain('[Main]');
    await page.locator('#export-dialog .icon-button').click();
    await page.reload();
    await expect(page.locator('#loading')).toBeHidden();
    await expect(page.locator('#deck-name')).toHaveValue('Imported beta');
    await expect(page.locator('#side-count')).toHaveText('2');
    await page.locator('#import-button').click();
    await application.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, exportedFile);
    await page.locator('#import-file').click();
    await expect(page.locator('#confirm-import')).toBeEnabled();
    await page.locator('#import-dialog .icon-button').click();
    await page.locator('#new-sidebar').click();
    await page.locator('#new-name').fill('Commander project');
    await page.locator('#new-format').selectOption('Commander');
    await page.locator('#new-form button[type=submit]').click();
    await expect(page.locator('#commander-section')).toBeVisible();
    await expect(page.locator('#practice-button')).toBeDisabled();
    expect(errors).toEqual([]);
    expect(fs.readdirSync(path.join(dataPath, 'decks')).filter(file => file.endsWith('.json'))).toHaveLength(3);
  } finally { await application.close(); }
});
