const { test } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { once } = require('node:events');
const { testProfile, startEngine, ready } = require('./support/engine.cjs');
const data = testProfile('engine');
const start = () => startEngine(data);

test('real Forge engine: persistence, revisions, import, export and practice', { timeout: 120000 }, async () => {
  let engine = start();
  try {
    await ready(engine);
    const all = await engine.request('search', { limit: 24 });
    assert.ok(all.total > 33000, `Expected the full catalog; got ${all.total}`);
    assert.equal(all.catalogTotal, all.total);
    assert.equal(all.cards.length, 24);
    const lastPage = await engine.request('search', { offset: all.total - 1, limit: 24 });
    assert.equal(lastPage.cards.length, 1);
    for (const [query, name] of [['Insectile Aberration', 'Delver of Secrets'], ['Nicol Bolas, the Arisen', 'Nicol Bolas, the Ravager'], ['Ach! Hans, Run!', '"Ach! Hans, Run!"']]) {
      const matches = await engine.request('search', { text: query, limit: 200 });
      assert.ok(matches.cards.some(card => card.name === name), `Missing ${query}`);
      assert.equal(matches.catalogTotal, all.total);
    }
    const planes = await engine.request('search', { type: 'Plane', limit: 200 });
    assert.ok(planes.cards.length > 0);
    assert.ok(planes.cards.every(card => card.deckSection === 'Planes'), 'Plane filtering must not match Planeswalker');
    const plane = (await engine.request('search', { text: 'The Eon Fog' })).cards.find(card => card.name === 'The Eon Fog');
    assert.equal(plane.deckSection, 'Planes');
    let state = await engine.request('new', { name: 'Persistence test', format: 'Constructed' });
    assert.equal(state.saveError, null);
    const deckId = state.id;
    const result = await engine.request('search', { text: 'Lightning Bolt', limit: 24, unique: true });
    assert.equal(result.cards[0].name, 'Lightning Bolt');
    assert.equal(result.cards.filter(card => card.name === 'Lightning Bolt').length, 1);
    const bolt = result.cards[0];
    state = await engine.request('edit', { revision: state.deck.revision, edits: [{ section: 'Main', cardId: bolt.id, quantity: 4 }] });
    const revision = state.deck.revision;
    await assert.rejects(engine.request('edit', { revision: revision - 1, edits: [{ section: 'Main', cardId: bolt.id, quantity: 1 }] }), /revision/);
    await assert.rejects(engine.request('edit', { revision, edits: [{ section: 'Main', cardId: bolt.id, quantity: 2 }, { section: 'Main', cardId: 'bad-id', quantity: 1 }] }), /Unknown printing/);
    assert.equal((await engine.request('snapshot')).deck.entries[0].quantity, 4);
    state = await engine.request('undo', { revision });
    assert.equal(state.deck.entries.length, 0);
    state = await engine.request('redo', { revision: state.deck.revision });
    assert.equal(state.deck.entries[0].quantity, 4);
    const bad = await engine.request('importPreview', { text: '4 Not A Real Magic Card XYZ' });
    assert.equal(bad.problems.length, 1);
    await assert.rejects(engine.request('import', { text: '4 Not A Real Magic Card XYZ', name: 'Bad' }));
    assert.equal((await engine.request('snapshot')).id, deckId);
    state = await engine.request('import', { text: 'Deck\n4 Lightning Bolt\n56 Mountain\nSideboard\n2 Shock', name: 'Real import', format: 'Constructed' });
    assert.equal(state.validation.valid, true);
    assert.equal(state.saveError, null);
    state = await engine.request('edit', { revision: state.deck.revision, edits: [{ section: 'Planes', cardId: plane.id, quantity: 1 }] });
    assert.equal(state.deck.entries.find(entry => entry.section === 'Planes').card.name, 'The Eon Fog');
    const forgeExport = await engine.request('export', { kind: 'forge' });
    assert.match(forgeExport, /\[metadata\][\s\S]*\[Main\][\s\S]*\[Sideboard\]/);
    assert.equal((await engine.request('importPreview', { text: forgeExport.split('\n').slice(2).join('\n') })).problems.length, 0);
    const exported = await engine.request('export', { kind: 'text' });
    assert.match(exported, /56 Mountain/);
    assert.equal((await engine.request('importPreview', { text: exported })).problems.length, 0);
    let practice = await engine.request('practice', { action: 'shuffle' });
    assert.equal(practice.hand.length, 7); assert.equal(practice.remaining, 53);
    practice = await engine.request('practice', { action: 'draw' });
    assert.equal(practice.hand.length, 8); assert.equal(practice.remaining, 52);
    practice = await engine.request('practice', { action: 'bottom', index: 0 });
    assert.equal(practice.hand.length, 7); assert.equal(practice.remaining, 53);
    const importedId = state.id;
    engine.close(); await once(engine.child, 'exit');
    engine = start(); await ready(engine);
    state = await engine.request('open', { id: importedId });
    assert.equal(state.deck.name, 'Real import');
    assert.equal(state.deck.canUndo, false);
    assert.equal(state.deck.entries.reduce((sum, entry) => sum + entry.quantity, 0), 63);
    assert.equal(state.deck.entries.find(entry => entry.section === 'Planes').card.name, 'The Eon Fog');
    assert.equal((await engine.request('list')).decks.length, 2);
    await assert.rejects(engine.request('open', { id: '../../outside' }));
    fs.writeFileSync(path.join(data, 'decks', 'broken.json'), '{');
    assert.equal((await engine.request('list')).problems.length, 1);
  } finally { engine.close(); }
});
