package forge.adventure.archipelago;

import com.google.common.collect.ImmutableMap;

import java.util.Map;

public class ItemRegistry {
    private static final Map<Long, String> DEFAULT_ITEMS = ImmutableMap.<Long, String>builder()
            .put(1L, "White rune")
            .put(2L, "Blue rune")
            .put(3L, "Black rune")
            .put(4L, "Red rune")
            .put(5L, "Green rune")
            .put(1000L, "Gold (S)")
            .put(1001L, "Gold (M)")
            .put(1002L, "Gold (L)")
            .put(1003L, "Mana Shards (S)")
            .put(1004L, "Mana Shards (M)")
            .put(1005L, "Mana Shards (L)")
            .put(1006L, "Bronze Challenge Coin")
            .put(1007L, "Silver Challenge Coin")
            .put(1008L, "Gold Challenge Coin")
            .put(1009L, "Set Unlock")
            .put(2000L, "Unlock White")
            .put(2001L, "Unlock Blue")
            .put(2002L, "Unlock Black")
            .put(2003L, "Unlock Red")
            .put(2004L, "Unlock Green")
            .put(3000L, "Chandra's Tome")
            .put(3001L, "Phoenix Charm")
            .put(3002L, "Demonic Contract")
            .put(3003L, "Piper's Charm")
            .put(3004L, "Sleep Wand")
            .put(3005L, "Hill Giant Club")
            .put(3006L, "Cursed Treasure")
            .put(3007L, "Farmer's Tools")
            .put(3008L, "Battle Standard")
            .put(3009L, "Hivestone")
            .put(3010L, "Life Amulet")
            .put(3011L, "Axt")
            .put(3012L, "Bronze Sword")
            .put(3013L, "Iron Boots")
            .put(3014L, "Iron Shield")
            .put(3015L, "Iron Armor")
            .put(3016L, "Steel Sword")
            .put(3017L, "Steel Boots")
            .put(3018L, "Steel Shield")
            .put(3019L, "Steel Armor")
            .put(3020L, "Armor of the Hivelord")
            .put(3021L, "Leather Boots")
            .put(3022L, "Jungle Shield")
            .put(3023L, "Sorin's Amulet")
            .put(3024L, "Dagger")
            .put(3025L, "Aladdin's Ring")
            .put(3026L, "Spell Book")
            .put(3027L, "Cursed Ring")
            .put(3028L, "Mithril Boots")
            .put(3029L, "Mithril Shield")
            .put(3030L, "Mithril Armor")
            .put(3031L, "Presence of the Hydra")
            .put(3032L, "Death Ring")
            .put(3033L, "Flame Sword")
            .put(3034L, "Mirror Shield")
            .put(3035L, "Dungeon Map")
            .put(3036L, "Aladdin's Lamp")
            .put(3037L, "Heart-Piercer")
            .put(3038L, "Wood Bow")
            .put(3039L, "Sandals")
            .put(3040L, "Gold Boots")
            .put(3041L, "Gold Shield")
            .put(3042L, "Gold Armor")
            .put(3043L, "Dark Boots")
            .put(3044L, "Dark Shield")
            .put(3045L, "Dark Armor")
            .put(3046L, "Blood Vial")
            .put(3047L, "Charm")
            .put(3048L, "Snack")
            .put(3049L, "Change")
            .put(3050L, "Treasure")
            .put(3051L, "Magic Shard")
            .put(3052L, "Mad Staff")
            .put(3053L, "Dark Amulet")
            .put(3054L, "Pandora's Box")
            .put(3055L, "Disrupting Scepter")
            .put(3056L, "Entrancing Lyre")
            .put(3057L, "Heavy Arbalest")
            .put(3058L, "Ring of Three Wishes")
            .put(3059L, "The Blackstaff of Waterdeep")
            .put(3060L, "Unerring Sling")
            .put(3061L, "Jeweled Amulet")
            .put(3062L, "Traveler's Amulet")
            .put(3063L, "Relic Amulet")
            .put(3064L, "Amulet of Kroog")
            .put(3065L, "Amulet of Vigor")
            .put(3066L, "Veilstone Amulet")
            .put(3067L, "Jandor's Ring")
            .put(3068L, "Jinxed Ring")
            .put(3069L, "Nine-Ringed Bo")
            .put(3070L, "Ring of Immortals")
            .put(3071L, "Prism Ring")
            .put(3072L, "Ring of Renewal")
            .put(3073L, "Kite Shield")
            .put(3074L, "Shell Wand")
            .put(3075L, "Manasight Amulet")
            .put(3076L, "Lightbringers Boots")
            .put(3077L, "Fortune Coin")
            .put(3078L, "White Staff")
            .put(3079L, "Black Staff")
            .put(3080L, "Blue Staff")
            .put(3081L, "Red Staff")
            .put(3082L, "Green Staff")
            .put(3083L, "Slimefoot's Slimy Staff")
            .put(3084L, "Kiora's Bident")
            .put(3085L, "Slime-Covered Boots")
            .put(3086L, "Amulet of the Deceiver")
            .put(3087L, "Jace's Signature Hoodie")
            .put(3088L, "Teferi's Staff")
            .put(3089L, "Garruk's Mighty Axe")
            .put(3090L, "Nahiri's Armory")
            .put(3091L, "Giant Scythe")
            .put(3092L, "Chicken Egg")
            .put(3093L, "Tibalt's Bag of Tricks")
            .put(3094L, "Xira's Fancy Hat")
            .put(3095L, "The Underworld Cookbook")
            .put(3096L, "Mantle of Ancient Lore")
            .put(3097L, "Zedruu's Lantern")
            .put(3098L, "Grolnok's Skin")
            .put(3099L, "Slobad's Iron Boots")
            .put(3100L, "Hallowed Sigil")
            .put(3101L, "Unhallowed Sigil")
            .put(4000L, "Sol Ring")
            .put(4001L, "Black Lotus")
            .put(4002L, "Mox Pearl")
            .put(4003L, "Mox Sapphire")
            .put(4004L, "Mox Jet")
            .put(4005L, "Mox Ruby")
            .put(4006L, "Mox Emerald")
            .put(5000L, "Cheat")
            .build();

    public static String getItem(Long input) {
        return DEFAULT_ITEMS.get(input);
    }
}
