package forge.util;

import forge.localinstance.properties.ForgeConstants;
import forge.localinstance.properties.ForgePreferences;
import forge.model.FModel;

import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Lazily-loaded index of which non-English languages exist for a given
 * paper Magic card printing, as recorded by Scryfall. Backed by the
 * resource generated by forge_scripts/update_languages.py
 * ({@link ForgeConstants#CARD_LANGUAGES_FILE}).
 * <p>
 * English is never stored: a card absent from the index, or missing a
 * given language's bit, is simply treated as "not confirmed available in
 * that language" and callers should fall back to English. This lets
 * {@code ImageFetcher} check, before contacting Scryfall, whether the
 * user's preferred card-image language actually exists for a given
 * card - avoiding pointless 404s (see issue #7382).
 */
public final class CardLanguageIndex {

    // Bit assignment must stay in sync with LANGUAGE_BITS in
    // forge_scripts/update_languages.py and ForgeConstants.getScryfallCardLanguageMapping()
    private static final Map<String, Integer> LANGUAGE_BITS = new HashMap<>();
    static {
        LANGUAGE_BITS.put("es", 1);
        LANGUAGE_BITS.put("fr", 1 << 1);
        LANGUAGE_BITS.put("de", 1 << 2);
        LANGUAGE_BITS.put("it", 1 << 3);
        LANGUAGE_BITS.put("pt", 1 << 4);
        LANGUAGE_BITS.put("ja", 1 << 5);
        LANGUAGE_BITS.put("ko", 1 << 6);
        LANGUAGE_BITS.put("ru", 1 << 7);
        LANGUAGE_BITS.put("zhs", 1 << 8);
        LANGUAGE_BITS.put("zht", 1 << 9);
    }

    private static volatile CardLanguageIndex instance;

    // setCode (lowercase) -> collectorNumber -> bitmask
    private final Map<String, Map<String, Integer>> index;

    public static CardLanguageIndex instance() {
        CardLanguageIndex result = instance;
        if (result == null) {
            synchronized (CardLanguageIndex.class) {
                result = instance;
                if (result == null) {
                    instance = result = new CardLanguageIndex(ForgeConstants.CARD_LANGUAGES_FILE);
                }
            }
        }
        return result;
    }

    CardLanguageIndex(String path) {
        this.index = load(path);
    }

    private static Map<String, Map<String, Integer>> load(String path) {
        final Map<String, Map<String, Integer>> result = new HashMap<>();
        final File file = new File(path);
        if (!file.isFile()) {
            System.err.println("CardLanguageIndex: no language index found at " + path
                    + " - all cards will be treated as English-only.");
            return result;
        }

        final List<String> lines = FileUtil.readFile(file);
        for (String line : lines) {
            if (line.isEmpty() || line.charAt(0) == '#') {
                continue; // blank line or "# meta ..." header
            }

            final String[] tokens = line.split(" ");
            if (tokens.length < 2) {
                continue;
            }

            final String setCode = tokens[0].toLowerCase();
            final Map<String, Integer> collectors = result.computeIfAbsent(setCode, k -> new HashMap<>());

            for (int i = 1; i < tokens.length; i++) {
                final int sep = tokens[i].lastIndexOf(':');
                if (sep <= 0) {
                    continue;
                }
                final String collector = tokens[i].substring(0, sep);
                try {
                    final int mask = Integer.parseInt(tokens[i].substring(sep + 1));
                    collectors.put(collector, mask);
                } catch (NumberFormatException ignored) {
                    // malformed entry, skip it rather than fail the whole load
                }
            }
        }
        return result;
    }

    /**
     * @param setCode         Scryfall set code (case-insensitive), e.g. from
     *                        {@code CardEdition.getScryfallCode()}
     * @param collectorNumber Scryfall collector number exactly as it would appear
     *                        in the download URL (i.e. already massaged the way
     *                        {@code ImageUtil.getScryfallDownloadUrl} does it)
     * @param langCode        Scryfall language code, e.g. "ja", "zhs", "ru"
     * @return true if this exact printing is confirmed to exist in that language,
     *         or if langCode is English (English is never stored, always assumed OK).
     *         false only means "not confirmed" - either the card/set isn't in the
     *         index yet, or it genuinely wasn't printed in that language.
     */
    public boolean isAvailableInLanguage(String setCode, String collectorNumber, String langCode) {
        if (langCode == null || langCode.isEmpty() || "en".equalsIgnoreCase(langCode)) {
            return true;
        }
        final Integer bit = LANGUAGE_BITS.get(langCode.toLowerCase());
        if (bit == null) {
            return false; // unrecognized language code
        }
        final Map<String, Integer> collectors = index.get(setCode.toLowerCase());
        if (collectors == null) {
            return false;
        }
        final Integer mask = collectors.get(collectorNumber);
        return mask != null && (mask & bit) != 0;
    }

    /**
     * @return the Scryfall language code the user selected in Preferences
     *         (UI_CARD_DOWNLOAD_LANG), or null if unset/English - in which case
     *         Forge should download exactly as it does today (no behavior change).
     */
    public static String getPreferredCardLangCode() {
        String pref = FModel.getPreferences().getPref(ForgePreferences.FPref.UI_CARD_DOWNLOAD_LANG);
        if (pref == null || pref.isEmpty() || "en".equalsIgnoreCase(pref)) {
            return null;
        }
        return pref;
    }

    /**
     * Convenience for call sites that only build a single download URL (as opposed to
     * {@code ImageFetcher}'s main card path, which tries the preferred language first and
     * keeps the default as a fallback candidate). Returns the preferred language if the user
     * has one set and this exact printing is confirmed to exist in it; otherwise returns
     * {@code defaultLangCode} unchanged, so English users (the default) see zero behavior
     * change from before this feature existed.
     */
    public static String resolvePreferredLangCode(String setCode, String collectorNumber, String defaultLangCode) {
        String preferred = getPreferredCardLangCode();
        if (preferred == null || preferred.equalsIgnoreCase(defaultLangCode)) {
            return defaultLangCode;
        }
        if (instance().isAvailableInLanguage(setCode, collectorNumber, preferred)) {
            return preferred;
        }
        return defaultLangCode;
    }
}
